const getCharById = require('../controllers/getCharById')
const {postUser} = require('../controllers/postUser')
const {login} = require('../controllers/login.js')
const {postFav} = require('../controllers/postFav')
const {deleteFav} = require('../controllers/deleteFav')
// const {postFav, deleteFav} = require('../controllers/handleFavorites')
// const login = require('../controllers/login')
const express = require('express')
const routes = express.Router()

routes.get('/character/:id', getCharById)
routes.post('/login',postUser)
routes.get('/login', login)
routes.post('/fav',postFav)
routes.delete('/fav/:id',deleteFav)
// routes.get('/login', login)
// routes.post('/fav',postFav)
// routes.delete('/fav/:id', deleteFav)

module.exports = routes